config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'
  devise_for :users
  resources :imagens
  resources :bodies
  resources :posts
  resources :categories
  root 'inicio#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/body.rb
class Body < ApplicationRecord
  belongs_to :post
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  before_action :set_body, only: [:show, :edit, :update, :destroy]

  # GET /bodies
  # GET /bodies.json
  def index
    @bodies = Body.all
  end

  # GET /bodies/1
  # GET /bodies/1.json
  def show
  end

  # GET /bodies/new
  def new
    @body = Body.new
  end

  # GET /bodies/1/edit
  def edit
  end

  # POST /bodies
  # POST /bodies.json
  def create
    @body = Body.new(body_params)

    respond_to do |format|
      if @body.save
        format.html { redirect_to @body, notice: 'Body was successfully created.' }
        format.json { render :show, status: :created, location: @body }
      else
        format.html { render :new }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bodies/1
  # PATCH/PUT /bodies/1.json
  def update
    respond_to do |format|
      if @body.update(body_params)
        format.html { redirect_to @body, notice: 'Body was successfully updated.' }
        format.json { render :show, status: :ok, location: @body }
      else
        format.html { render :edit }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodies/1
  # DELETE /bodies/1.json
  def destroy
    @body.destroy
    respond_to do |format|
      format.html { redirect_to bodies_url, notice: 'Body was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_body
      @body = Body.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def body_params
      params.require(:body).permit(:information, :position, :post_id)
    end
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/views/bodies/_form.html.erb
<%= form_with(model: body, local: true) do |form| %>
  <% if body.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(body.errors.count, "error") %> prohibited this body from being saved:</h2>

      <ul>
        <% body.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_area :information %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bodies/edit.html.erb
<h1>Editing Body</h1>

<%= render 'form', body: @body %>

<%= link_to 'Show', @body %> |
<%= link_to 'Back', bodies_path %>

app/views/bodies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bodies</h1>

<table>
  <thead>
    <tr>
      <th>Information</th>
      <th>Position</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bodies.each do |body| %>
      <tr>
        <td><%= body.information %></td>
        <td><%= body.position %></td>
        <td><%= body.post_id %></td>
        <td><%= link_to 'Show', body %></td>
        <td><%= link_to 'Edit', edit_body_path(body) %></td>
        <td><%= link_to 'Destroy', body, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Body', new_body_path %>

app/views/bodies/new.html.erb
<h1>New Body</h1>

<%= render 'form', body: @body %>

<%= link_to 'Back', bodies_path %>

app/views/bodies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Information:</strong>
  <%= @body.information %>
</p>

<p>
  <strong>Position:</strong>
  <%= @body.position %>
</p>

<p>
  <strong>Post:</strong>
  <%= @body.post_id %>
</p>

<%= link_to 'Edit', edit_body_path(@body) %> |
<%= link_to 'Back', bodies_path %>